name: test_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter
  
  core:
    path: core
  core_ui:
    path: core_ui

  local_logger:
    path: features/local_logger

dev_dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.15.2
